events {
    worker_connections 1024;
}

http {
    upstream flask_app {
        # Using a Unix socket for communication with uWSGI
        server unix:///tmp/sockets/uwsgi.sock;
    }

    server {
        listen 80;
        server_name your_domain.com; # Add your domain name here

        # Main application location
        location / {
            include uwsgi_params;
            uwsgi_pass flask_app;
        }

        # Socket.IO specific location block
        location /socket.io/ {
            # Standard proxy settings
            proxy_pass http://flask_app;
            proxy_redirect off;

            # WebSocket-specific headers for the upgrade
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        # Static files location
        location /static {
            alias /app/static;
        }
    }
}