[uwsgi]
# uWSGI configuration
module = app:app
master = true
processes = 4
die-on-term = true

# SocketIO specifics
socket = /tmp/sockets/uwsgi.sock
chmod-socket = 666
http-socket = 127.0.0.1:5000
gevent = 1000
gevent-monkey-patch = true