events {
    worker_connections 1024;
}

http {
    upstream flask_app {
        server unix:///tmp/sockets/uwsgi.sock;  # CHANGE THIS LINE
    }

    server {
        listen 80;

        location / {
            include uwsgi_params;
            uwsgi_pass flask_app;
        }

        location /static {
            alias /app/static;
        }
    }
}